MBP-360 - Biocode Plugin 2.4.4: NoSuchMethodError when using 7.0.1 (group 7998) Re-add javaee.jar.  Apparently it is required at runtime?
git-svn-id: svn+ssh://svn.biomatters.com/usr/local/svnroot/geneious/trunk/plugins/MooreaLabBench@60564 84f1a7b3-ea07-0410-887d-f1e6e76816dd